<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_fa fa-eye-slash pwd_icon</name>
   <tag></tag>
   <elementGuidId>14e2e103-695d-46f0-be99-b5f9d71c85a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye-slash.pwd_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/div[3]/div[2]/div[3]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3ee5a2b0-900e-4fc9-a641-ec81addc8c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmLogin.toggleShowPassword()</value>
      <webElementGuid>995fb6f2-9f3e-476b-a4c0-0f12f9eeab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye-slash pwd_icon</value>
      <webElementGuid>a1b928cb-e31b-437b-8568-778780e11f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/div[@class=&quot;login_form col-xs-12&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-2 col-xs-12 full_login&quot;]/div[@class=&quot;login_right col-sm-6 col-xs-12&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-xs-12 static_txt p-0 ng-scope&quot;]/i[@class=&quot;fa fa-eye-slash pwd_icon&quot;]</value>
      <webElementGuid>21a95af8-0f4b-4875-a615-23fa07b3852d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[2]/div[3]/div[2]/div/i</value>
      <webElementGuid>253c21c7-7c96-4e19-97fb-e78665dbc232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>8b1a2ec6-d0ef-4234-9aa4-222c3d71f3ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
