<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>35c1d48f-072c-48c4-9b40-45c108e07aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.custom-create.ctt.m-l-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[3]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c5c47aa-66e1-4b56-85e3-fb5fb904715c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmSlot.getChosenFilters(vmSlot.chosenFiltersForm.$valid)</value>
      <webElementGuid>2e96ccbe-26be-4cf9-8c04-b2d340df2223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-create ctt m-l-10</value>
      <webElementGuid>eef8412b-5904-43dc-bb9c-5762956a7f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>93d62503-3a1c-4894-9496-f2541fbb84d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;btn_action m-0&quot;]/span[1]/a[@class=&quot;custom-create ctt m-l-10&quot;]</value>
      <webElementGuid>48ba41d4-c1f0-48c4-9973-13c1b2bf138d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[3]/span/a</value>
      <webElementGuid>2665c7dc-e3bf-44e6-8935-af5465c851d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go')]</value>
      <webElementGuid>2a189433-3f27-46fb-95b7-72ceaec44748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::a[1]</value>
      <webElementGuid>bdfab50c-29ad-4488-b96e-7a30dafc7269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar view'])[1]/preceding::a[1]</value>
      <webElementGuid>c20fc3e7-4eed-452b-9c14-e411ee904145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>a226550f-3908-44fd-a2c4-e5b9d8256a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>52749640-7446-4606-98c7-00fa9736da96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>581b6d47-f796-4f97-8090-68972507e655</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
