<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1aeadfec-c774-43ac-964f-60a7fd81b534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > p.m-0 > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec0a6b80-6f77-441a-a196-cc339b326580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>content/css/img/m-cal-iconnew.png</value>
      <webElementGuid>7646d9ce-dd12-4308-ba44-3f61a8a8c632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;manage_partner&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-md-12 col-sm-12 dashboard cal_view p-b-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-12&quot;]/div[@class=&quot;customm-r&quot;]/ul[@class=&quot;filter-choose flexinline&quot;]/li[2]/p[@class=&quot;m-0&quot;]/a[1]/img[1]</value>
      <webElementGuid>2ef7220f-6f6d-41af-914a-d52e034a5c5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/p/a/img</value>
      <webElementGuid>258837ca-156b-4c88-94c4-94bd00a6ccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'content/css/img/m-cal-iconnew.png']</value>
      <webElementGuid>f444e99a-334d-4cee-8848-a793e74ce436</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
