<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>00645066-2608-4450-921c-9c1b16f0ebde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.m-0 > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>03f70261-38d6-4bc0-aa0b-4934f478e053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>content/css/img/da-cal-iconnew.png</value>
      <webElementGuid>900e8811-d571-483c-b93d-b85f7d2cd78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;manage_partner&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-md-12 col-sm-12 dashboard cal_view p-b-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-12&quot;]/div[@class=&quot;customm-r&quot;]/ul[@class=&quot;filter-choose flexinline&quot;]/li[1]/p[@class=&quot;m-0&quot;]/a[1]/img[1]</value>
      <webElementGuid>0825dc69-0106-4af0-a01d-9732f2c8ca89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>3e84cb8e-b5d4-4af7-a3c0-f2b2d9ce7343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'content/css/img/da-cal-iconnew.png']</value>
      <webElementGuid>dbbb5dc6-2b8a-40e8-96c2-575f139e00ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
