<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month                               _d53c4c</name>
   <tag></tag>
   <elementGuidId>98104766-b081-480a-87d8-d41b592bdcae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7cff91ff-4e89-483a-b3fb-b55665a22d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control m-r-5 ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>ebd50785-7780-4b7b-9408-e5fa8a4d063a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>9c88b8f5-41b8-4a04-a84e-0e4642eacc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Browse by Month</value>
      <webElementGuid>0da7669e-46a9-4ec5-8efd-c4c62b2ea3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmSlot.ChoosefilterData.Month</value>
      <webElementGuid>20394b5d-1897-4dc7-9af7-7b4d2d043797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                </value>
      <webElementGuid>2e602154-e9ab-46a9-b6d9-2b273e08cd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;browse position-relative&quot;]/select[@class=&quot;minimal form-control m-r-5 ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>374fe8ed-72b9-4da8-8220-fb63e125e7b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Month']</value>
      <webElementGuid>bf1a5396-e332-4ef5-9c14-fd8aad9ffac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div/select</value>
      <webElementGuid>18cf559c-cca2-47c7-9fe3-07dcf2462db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::select[1]</value>
      <webElementGuid>d9068bb4-953e-4012-8c12-139c1a480ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[2]</value>
      <webElementGuid>cdaff86c-3708-41ff-8358-5713bd9423e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>703f38fc-c6c0-48d7-b9fa-20b9d342ae34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Month' and @placeholder = 'Browse by Month' and (text() = '
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                ' or . = '
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                ')]</value>
      <webElementGuid>a99519d7-9abb-4c59-8c0a-46d8cf122c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
