<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year                                _78bea1</name>
   <tag></tag>
   <elementGuidId>9a0f1a00-87f2-4d0b-82c4-3c3da7c64cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Year&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2102dc1-970a-4163-84e1-f2a7cde3b274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>c0a6514e-3efc-4dab-9818-3553e355e555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>ab91f1bd-b55d-47ab-8b68-56ae949ee8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmSlot.ChoosefilterData.Year</value>
      <webElementGuid>d523af2d-8272-477d-b527-6641c1442011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                </value>
      <webElementGuid>01a0cfbb-e0c8-4509-9fd6-8d5c07f13ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;browse position-relative&quot;]/select[@class=&quot;minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>345fd642-d15e-492e-9836-c27fc4acf337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Year']</value>
      <webElementGuid>6bf5efac-88db-4828-a83d-46e1a6a689cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[2]/select</value>
      <webElementGuid>0275a3cd-22f7-453f-b894-39e99b3e5c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::select[2]</value>
      <webElementGuid>137257a5-d713-43e5-93b5-448de7853b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>82bf682e-1763-4ce5-b67a-0387930fcafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>75832f70-fcea-4fb3-b89e-9b5426f4aa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Year' and (text() = '
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                ' or . = '
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                ')]</value>
      <webElementGuid>b8e7dfd5-5db6-4201-a3a0-2d2f33a16013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
