<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save</name>
   <tag></tag>
   <elementGuidId>e8175185-8e24-4789-ba72-474ed5fbf6fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99d24801-f413-456a-8c99-9dd206d1613c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctt custom-create m-r-10 ng-scope</value>
      <webElementGuid>c6eaf69a-1754-45c9-b41d-5c1014e0a0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vmSlot.loadingShow</value>
      <webElementGuid>77746d2d-9fd7-4f56-b70b-79307fb8dd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmSlot.fnAddSlot(vmSlot.addSlotForm.$valid)</value>
      <webElementGuid>72f04aa6-dfce-4dce-91fe-d3bd15e179c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>15a7efd5-4bf8-41b6-98f2-f08152dac7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>2a15bf45-9e6e-4b0e-a4ea-7420ad8200da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 text-align-center m-t-15&quot;]/a[@class=&quot;ctt custom-create m-r-10 ng-scope&quot;]</value>
      <webElementGuid>7578f6ca-460e-463c-b977-cae020dab7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Save']</value>
      <webElementGuid>4b9d73d5-09b2-444f-ba28-9fa437bdbc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[4]/a</value>
      <webElementGuid>a20a1646-b83f-46d2-90f9-57c65687b6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Save')]</value>
      <webElementGuid>d6ce50da-f226-43f4-9f64-cd2f4a5fff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::a[1]</value>
      <webElementGuid>72a0a021-0790-4605-9454-8f86754b2d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::a[1]</value>
      <webElementGuid>2ff12716-34ef-4d23-8c78-1831ebad8a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>12c1f892-c425-4e70-9363-e9250fd71610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>733be044-bc0e-4f1a-beff-5aabd3d8e42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>59f61766-91b1-4339-ac5c-9c4c6c8d3799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Save' and (text() = ' Save' or . = ' Save')]</value>
      <webElementGuid>f4ad8bc1-6983-4413-905f-e24763f6ec7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
