<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Today</name>
   <tag></tag>
   <elementGuidId>d89d8694-7677-4528-ae84-636330949073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-info.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[48]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec9d1c36-fa09-4511-83be-55e54c0833c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ddcb0bf-7737-4feb-a965-6c17c8b39f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-info ng-binding</value>
      <webElementGuid>71ca936f-5729-4d58-9f91-c80358629ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>select('today')</value>
      <webElementGuid>acb2698a-1cf0-4674-90a8-56c4ea118427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isDisabled('today')</value>
      <webElementGuid>c5da1e05-c4ac-41b0-b380-02d939a3daa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>9405c0a5-b577-4270-a4dc-666232ab9309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12  m-t-15&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6 custom_date&quot;]/div[@class=&quot;input-group&quot;]/ul[@class=&quot;dropdown-menu ng-pristine ng-untouched ng-valid ng-scope ng-valid-date-disabled&quot;]/li[@class=&quot;ng-scope&quot;]/span[@class=&quot;btn-group pull-left&quot;]/button[@class=&quot;btn btn-sm btn-info ng-binding&quot;]</value>
      <webElementGuid>759cf70c-f80b-4469-8200-57a7310e2783</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[48]</value>
      <webElementGuid>34c11617-9ed3-4710-856f-cd5cbdef5bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[2]/div/div/div/ul/li[2]/span/button</value>
      <webElementGuid>05286f9e-7471-4bd0-a476-921c468d2962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[2]/following::button[43]</value>
      <webElementGuid>bd242ff3-2767-4172-8260-d512c2c7ab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[2]/following::button[43]</value>
      <webElementGuid>052a5ad9-2cc3-441f-a438-eef00bfd55b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::button[1]</value>
      <webElementGuid>c6155c5a-2b75-431c-8e81-2663fcf7c099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[2]</value>
      <webElementGuid>2a2dd453-1e86-4545-975a-e551a8c86b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>864e0d95-20c4-4a48-a42d-01cf528ead5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>b41d42c9-60cc-419c-88d5-447504a3f544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>4f81782a-b323-4db6-bc77-b3a3ee5aeace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
