<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>end time</name>
   <tag></tag>
   <elementGuidId>46817a6b-8265-4003-83a7-1d857bf30e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;EndTime&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='EndTime' or @class ='minimal form-control ng-touched ng-dirty ng-valid-parse ng-valid-required ng-pristine ng-untouched ng-invalid ng-invalid-required'] </value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>69cc23bb-75d4-4f0a-9f80-3c1d5b81ac22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-touched ng-dirty ng-valid-parse ng-valid-required ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>905ccd52-cd17-4890-a84a-9bc0c084056c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EndTime</value>
      <webElementGuid>f8d1e336-8046-4654-8433-d1dc6e966011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.EndTime</value>
      <webElementGuid>db8d57ed-4804-40b5-8ef8-2c559dc5afee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>cf0145d8-748c-46c8-bafe-f5e61c42b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                </value>
      <webElementGuid>603f16fd-5900-4562-a6c3-3dd59103d935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 p-l-0&quot;]/select[@class=&quot;minimal form-control ng-touched ng-dirty ng-valid-parse ng-valid-required ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>b71bdf18-903d-4f9e-b42f-2bfd0ee8d8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='EndTime']</value>
      <webElementGuid>ae5eb659-5f74-431c-8646-c27879843113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div[2]/div/select</value>
      <webElementGuid>24a71e97-e25c-41c9-a32c-b7eda2ee5fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::select[1]</value>
      <webElementGuid>23d7acd5-01a4-4d4b-8cc4-7d925c2325d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[3]</value>
      <webElementGuid>bc9d9647-9a42-4286-9ea9-77f7c87f9e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[2]</value>
      <webElementGuid>d8825a4c-27b0-493c-8fa5-0de67eb5d72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[2]</value>
      <webElementGuid>72adaffe-8b33-426e-a900-c62d9337886c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>e577a124-252a-4dd8-9090-366d023a4736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'EndTime' and (text() = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ' or . = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ')]</value>
      <webElementGuid>5f6d0288-6aa4-4bd8-ad6f-7528366fb712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
