<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Option                              _264d98_1</name>
   <tag></tag>
   <elementGuidId>bbcb4593-634e-439a-8939-9919bbe00ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;EndMeridiem&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='EndMeridiem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4fdb598f-8bb0-4f80-b66a-c2dec4e83f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>a1101bb0-68fe-4994-a236-7ee62cc480a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EndMeridiem</value>
      <webElementGuid>e32c0b5e-bf7b-4319-90c2-af26201a3dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.EndMeridiem</value>
      <webElementGuid>c06dba1a-60c1-4cd9-a170-366cb74e5f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>bb3b08df-d9bc-4f83-b8f5-a0660abf0337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Option
                                    AM
                                    PM
                                </value>
      <webElementGuid>c9c30ece-5cb5-4b10-8aa2-3fe178e1bf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 nopadding&quot;]/select[@class=&quot;minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>6d8dce16-b260-46ad-9c43-c447a71212b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='EndMeridiem']</value>
      <webElementGuid>af1288e9-db5d-4442-afae-1bcdb85375bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div[2]/div[2]/select</value>
      <webElementGuid>3209018c-6325-4f5c-972c-2831911b3fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::select[2]</value>
      <webElementGuid>9c7e1bb7-3eec-4efb-b14e-22edd1f9f343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[4]</value>
      <webElementGuid>a2c97cc2-3d93-4900-ae3b-75c399cc850d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>903d06fc-6b0c-4cd3-a0e2-c59def14722e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>b9070f7c-e7ed-46b6-a2e1-7a7689f00504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>1eb53caa-d423-44e1-9f03-649a6e0c96be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'EndMeridiem' and (text() = '
                                    Option
                                    AM
                                    PM
                                ' or . = '
                                    Option
                                    AM
                                    PM
                                ')]</value>
      <webElementGuid>a79c0cf1-ea82-4f3e-bc7d-6df21cb35803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
