<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Time                                _48fbf9</name>
   <tag></tag>
   <elementGuidId>f08079bb-f96e-4143-8e85-644f31b812fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;StartTime&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='StartTime' or @class='minimal form-control ng-touched ng-dirty ng-valid-required ng-valid-parse ng-pristine ng-untouched ng-invalid ng-invalid-required']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67b92d0e-58a2-4862-a158-1412a3641e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-touched ng-dirty ng-valid-required ng-valid-parse ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>1d467079-e2e7-4fb1-8724-e0118c9d54e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartTime</value>
      <webElementGuid>fa437b0a-8daf-4c55-a3f0-788f89a711b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.StartTime</value>
      <webElementGuid>7809ebcd-2750-47fd-ad98-79efc44ef19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>811ad3eb-c74c-4ab0-ac46-4d1663e5fc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                </value>
      <webElementGuid>008b2005-38f5-49f3-9a9b-8b5ac983c989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 p-l-0&quot;]/select[@class=&quot;minimal form-control ng-touched ng-dirty ng-valid-required ng-valid-parse ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>f3719a81-417b-4509-a663-95e8e5d4cb7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='StartTime']</value>
      <webElementGuid>ea5c82b6-5125-48de-85f1-cfdb2b402a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div/div/select</value>
      <webElementGuid>d6a2217f-ed5b-4238-a356-8f216cf7376c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>cdeffa6b-046b-47d2-a4da-b59e41d28e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::select[2]</value>
      <webElementGuid>c8a990b1-2bf4-4f52-bd67-6c720488034e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[4]</value>
      <webElementGuid>36cc9537-2b29-4869-b786-fae1d867b41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/select</value>
      <webElementGuid>d52ed28a-c999-45c4-a710-934c0c311fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'StartTime' and (text() = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ' or . = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ')]</value>
      <webElementGuid>fa817b15-56a4-4cc5-8bda-a8a41e99f5a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
