<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Option                              _264d98</name>
   <tag></tag>
   <elementGuidId>6acc9132-f334-4b5b-96ba-7f7a20789d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;StartMeridiem&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='StartMeridiem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd64ae00-43ab-4307-8230-2a239830606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>74cd7449-994e-412c-a8c1-9af57bb4ec8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartMeridiem</value>
      <webElementGuid>021e303f-f07a-46ac-8595-0181a551373f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.StartMeridiem</value>
      <webElementGuid>80125cc1-a818-4cf0-a5df-3cd13d22b35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>76e7d0b7-9556-49b0-b0d9-aa123924bfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    
                                    Option
                                    AM
                                    PM
                                </value>
      <webElementGuid>df091d86-9a94-4e76-b473-6b97fad63083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 nopadding&quot;]/select[@class=&quot;minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>cd140a3a-6a8c-422e-91b5-70de7d257be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='StartMeridiem']</value>
      <webElementGuid>f21e619c-5eeb-4fbc-9a95-2ac339c46597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div/div[2]/select</value>
      <webElementGuid>35cb44fc-fa19-460e-b93e-ce61043544c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[2]</value>
      <webElementGuid>d7a90e83-6a03-46aa-8c85-45e1b15bb600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::select[1]</value>
      <webElementGuid>f627fe9e-07e9-45c3-9c3f-bcabe1cd369a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[3]</value>
      <webElementGuid>b5c9f83a-6249-4e62-8292-36522434e530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/select</value>
      <webElementGuid>a5b08568-be16-4d5c-b102-a525df634d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'StartMeridiem' and (text() = '
                                    
                                    Option
                                    AM
                                    PM
                                ' or . = '
                                    
                                    Option
                                    AM
                                    PM
                                ')]</value>
      <webElementGuid>cf1b1222-73fb-4b03-8f78-293f9ad78323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
