<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Archived_204</name>
   <tag></tag>
   <elementGuidId>691686fb-ee6f-4cec-99b7-e6ba39dc38c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;204&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='204']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53aea537-792a-4b53-953d-ae55cb8481cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a4726760-79f1-4e22-9339-1562d41c75f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Self-Funded</value>
      <webElementGuid>e203de6a-cc01-4dc0-8a45-8c2110c4588e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmParticipant.FilterStatus</value>
      <webElementGuid>6d7ef0cd-3dc0-443d-9216-9c06e7cdbb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.FilterPendingStatus(status)</value>
      <webElementGuid>4e0df4d3-bd6b-476b-97f1-7f2d29ff32b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-4 ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>3b158d4c-7c2d-41d4-abbc-7b90b9f8098f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>204</value>
      <webElementGuid>770fe901-7651-4c7b-8d4e-3b0481a03630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;participant_grid_checklist&quot;]/div[@class=&quot;ng-scope col-md-7&quot;]/div[@class=&quot;showingresult text-align-right&quot;]/div[@class=&quot;r_checklist&quot;]/label[@class=&quot;ng-scope&quot;]/input[@class=&quot;m-t-4 ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>7075de0a-9043-4331-a6c1-412010dcf071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='204']</value>
      <webElementGuid>0a5c3863-440a-4a3d-82c1-e66ba5506153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[7]/input</value>
      <webElementGuid>b5e18902-98d8-4500-b7d5-87920e1fa427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = '204']</value>
      <webElementGuid>d9484acb-38e1-4cc9-8b12-246b076ea36c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
