<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected_200</name>
   <tag></tag>
   <elementGuidId>b5be7307-81f3-4aa6-a110-b9865f7bf296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;200&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='200']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7db0f150-278e-471e-ba32-1a62539af120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1b8990e9-3b02-40d0-8785-e92ce378971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Inprogress</value>
      <webElementGuid>7242608f-eb54-496c-abd7-f696fc984c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmParticipant.FilterStatus</value>
      <webElementGuid>c1101ba6-6a91-4035-b854-5973f0e8269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.FilterPendingStatus(status)</value>
      <webElementGuid>dd9d1758-f6b5-4048-aeb4-ebc38c617dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-4 ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>e4123ded-f55c-4cc0-8457-3364ad782436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>882a84ba-dc29-4061-b615-883126927283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;participant_grid_checklist&quot;]/div[@class=&quot;ng-scope col-md-7&quot;]/div[@class=&quot;showingresult text-align-right&quot;]/div[@class=&quot;r_checklist&quot;]/label[@class=&quot;ng-scope&quot;]/input[@class=&quot;m-t-4 ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>303908eb-68ee-4120-9e58-892e5a7ca3c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='200']</value>
      <webElementGuid>3775ad06-e22c-43cb-8337-fe717ddccc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]/input</value>
      <webElementGuid>70700673-6779-445c-90a2-3499134e40d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = '200']</value>
      <webElementGuid>e59d1ca0-5ddf-4c16-85dc-86eaeb0955c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
