<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Onboarding</name>
   <tag></tag>
   <elementGuidId>94aaa012-4c28-4756-8aaa-4639d7d3f29d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.open_manage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cd3c35c-7a5c-4c80-9e02-f618f17c4b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Neighbourhood') || isActive('/AddNeighbourhood') || isActive('/Worksite') || isActive('/AddWorksite') || isActive('/AddHousing') || isActive('/Housing') || isActive('/Partner') || isActive('/Participant') || isActive('/Employer') || isActive('/AddEmployer') || isActive('/EmployerForm') || isActive('/Staff') || isActive('/AddStaff') || isActive('/Participant') || isActive('/AddParticipant') || isActive('/SelfFundedForm') || (loggedUserType === 'Partner' &amp;&amp; isActive('/Staff')) || (loggedUserType === 'Partner' &amp;&amp; isActive('/AddStaff'))) &amp;&amp; OnboardingHeaderActive)}</value>
      <webElementGuid>1be7a5b6-cfa1-4f32-a5c3-db465a9369ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>a3bf3f2f-1ef9-4114-9caf-1f7e98480290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open_manage</value>
      <webElementGuid>89aa5daf-8b8d-4ff6-8fd4-8bc142a7715f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onboarding</value>
      <webElementGuid>d5bc991c-18f3-4794-bcfa-0caf00971fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/section[@class=&quot;bs-docs-nav navbar navbar-static-top nomargin manage_partner bb- ng-scope&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-left right_nav m-l-20 ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;open_manage&quot;]</value>
      <webElementGuid>1613e578-6c3b-4f8d-9134-a5889df744ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      <webElementGuid>2def87f3-142b-455d-b571-1c727f830e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Onboarding')]</value>
      <webElementGuid>580f13cc-9aef-450c-aeff-a346e1cf598f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>3db5e361-005e-4e76-8724-b27c5265c835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positions'])[1]/preceding::a[1]</value>
      <webElementGuid>04a59b17-5a5d-4f33-b27c-d4c84802660e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::a[2]</value>
      <webElementGuid>1c224747-7718-4c95-8142-2ed39e58aa97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Onboarding']/parent::*</value>
      <webElementGuid>9d3b176d-9e4c-40e8-896e-7ca858e18529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>66516b0e-b27d-4996-9075-fcab7fb60b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>ba6fdca3-5436-4857-ab8c-b506fb7c647a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Onboarding' or . = 'Onboarding')]</value>
      <webElementGuid>5c80c7bf-f9c8-4326-aa37-ed634fd95b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
