<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Partners</name>
   <tag></tag>
   <elementGuidId>69b1a475-6ca8-4359-8b5a-0d40da6d2ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='bs-navbar']/ul/li/a)[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav.navbar-right.col-md-push-3.ng-scope > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1182ee84-cdd2-4708-973e-4599252b38ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Partner') || isActive('/createPartner')) &amp;&amp; OnboardingPartnerActive)}</value>
      <webElementGuid>490c2618-a503-4790-ad17-5fcd37811a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Partner</value>
      <webElementGuid>a1f119be-fffd-4d39-8538-5de5aafb0a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partners</value>
      <webElementGuid>e1c1397e-a5a4-499c-b811-f70be3527f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/div[@class=&quot;col-xs-12 ng-scope&quot;]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-right col-md-push-3 ng-scope&quot;]/li[1]/a[1]</value>
      <webElementGuid>0bbbcec3-274e-4f41-acb9-eda85e67b574</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='bs-navbar']/ul/li/a)[12]</value>
      <webElementGuid>4b232156-f532-48a0-8d06-5c3edbb4eb3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Partners')]</value>
      <webElementGuid>5b7a8fab-ac88-41df-8a86-224b062597f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optisol Admin'])[1]/following::a[2]</value>
      <webElementGuid>597136c5-fc00-4ee3-aca6-b5bc4aa3d1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::a[4]</value>
      <webElementGuid>36a23388-b1a7-4801-98dd-7fb109beb201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[1]/preceding::a[1]</value>
      <webElementGuid>0f186fa0-2afb-4e86-8c8b-b756d1d7bf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/preceding::a[2]</value>
      <webElementGuid>539ef543-d8c4-4ddd-937a-5fbe551a21b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Partners']/parent::*</value>
      <webElementGuid>6d658a54-60e1-4eb8-b2d0-7d5f94508ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/Partner')])[2]</value>
      <webElementGuid>18d5ae50-294d-4eef-b790-d98dbb4ec9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/ul/li/a</value>
      <webElementGuid>846c359c-33b6-4659-b407-3152a8ec981b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Partner' and (text() = 'Partners' or . = 'Partners')]</value>
      <webElementGuid>aa47e790-2b40-4c0e-b4c5-52676000840f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
