<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_fa fa-eye pwd_icon</name>
   <tag></tag>
   <elementGuidId>38c5ea3f-c833-46ee-8fc7-c81569dd3005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-eye.pwd_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/div[3]/div[2]/div[3]/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ba30fa7d-9b0a-4e34-a2b9-4904560c8ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmLogin.toggleShowPassword()</value>
      <webElementGuid>69622ed7-f2cc-4444-8aaf-8bc6ab532c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye pwd_icon</value>
      <webElementGuid>30e43800-b15a-4cbf-b73e-b0562b087f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/div[@class=&quot;login_form col-xs-12&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-2 col-xs-12 full_login&quot;]/div[@class=&quot;login_right col-sm-6 col-xs-12&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-xs-12 static_txt p-0 ng-scope&quot;]/i[@class=&quot;fa fa-eye pwd_icon&quot;]</value>
      <webElementGuid>6f4f7c5e-0868-4968-a6d4-cb21839586c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[2]/div[3]/div[2]/div/i</value>
      <webElementGuid>5c989e7a-1e7b-4369-ad23-35777c3ad8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>9bb2eb40-2d23-4ee6-97ce-dc28be5109c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
