<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>52898345-14a5-4314-a30d-4c5c7c957918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmDashboard.addReminderForm']/div[4]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.help_btn.back_minwdth.float-right.fs-12.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bef2764-8693-4ab0-862f-4705b9d5e042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn help_btn back_minwdth float-right fs-12 ng-scope</value>
      <webElementGuid>2811c115-20e7-4f11-bb8f-bfccc117cb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vmDashboard.ReminderLoading</value>
      <webElementGuid>fe31726a-4758-4807-b637-3f339ac4fa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmDashboard.SaveReminder(vmDashboard.addReminderForm.$valid)</value>
      <webElementGuid>4e1da3e6-7b22-4c44-a61d-1d33fa2720e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>0f0f8aa3-f2f9-4e24-a6de-934712bbd1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmDashboard.addReminderForm&quot;)/div[@class=&quot;clearfix col-xs-12 cal_div&quot;]/button[@class=&quot;btn help_btn back_minwdth float-right fs-12 ng-scope&quot;]</value>
      <webElementGuid>9cb5b546-7d2e-43b8-b7e7-eeada76a32eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmDashboard.addReminderForm']/div[4]/button[2]</value>
      <webElementGuid>f5ad5517-e561-4b14-bc7b-256c110aacf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard'])[1]/following::button[1]</value>
      <webElementGuid>ae6632aa-c22f-42cb-9ebc-329741646e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Reminder'])[1]/following::button[3]</value>
      <webElementGuid>ee6e03be-ac40-4d13-97ba-f8ac70ac77c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oneworld@yopmail.com'])[1]/preceding::button[1]</value>
      <webElementGuid>ac9d841f-913b-461b-a288-97c3ec4a0832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>74475e81-16df-44df-bcf6-048de96cf655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4e2a2c74-4f05-4369-b722-27663a4d4487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>167da034-0839-47b4-9229-c391b773dcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
