<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Reminder_Title</name>
   <tag></tag>
   <elementGuidId>151da0fd-835e-4f89-a4af-424d9a1eee59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d14b4e56-8dcc-433b-9fd7-d90f6694685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_input ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>0bc5a4f6-ad72-43ad-8714-0bfba5affbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72304b1a-01a0-451b-9af4-e1eec1f758a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>accbcdeb-060b-444d-9a17-0e9b210f7481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmDashboard.AddReminderData.Title</value>
      <webElementGuid>a05e0336-77dc-4bc9-834f-2a54bc99c982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>c977160b-5355-4522-8aa7-814e7a585d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmDashboard.addReminderForm&quot;)/div[@class=&quot;col-xs-12 m-t-15 nopadding&quot;]/div[@class=&quot;col-xs-12 p-0&quot;]/input[@class=&quot;style_input ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>3d7701a2-f4c5-4038-8666-2948da3bcea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Title']</value>
      <webElementGuid>d6112d13-711e-40bd-9b55-37439bb9ffe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmDashboard.addReminderForm']/div/div/input</value>
      <webElementGuid>359b3bd8-fd5b-4d46-8804-6bda3c5daa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4d134669-1009-49e0-a8d9-d21af4cdfde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Title' and @placeholder = 'Title']</value>
      <webElementGuid>22d267fd-0d01-40bb-88f6-85ae4ef6c58d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
