<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Add Reminder_Notes</name>
   <tag></tag>
   <elementGuidId>d905936d-b4fd-46e3-92e2-4334080fcce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='Notes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;Notes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b1de937e-d74d-41b8-9d7c-045e8121e4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>e15297fd-32b0-4388-bfd6-04a2a4d96d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control style_input m-t-15 ng-untouched ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>eeea70ad-a1b9-4eae-b0fa-212a4c827e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>8456439c-4a89-4255-81d1-410e0b8991fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmDashboard.AddReminderData.Notes</value>
      <webElementGuid>0a9e2efc-4507-412c-8bad-d5a31db2392b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmDashboard.addReminderForm&quot;)/div[@class=&quot;col-xs-12 m-t-15 nopadding&quot;]/textarea[@class=&quot;form-control style_input m-t-15 ng-untouched ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]</value>
      <webElementGuid>7cbcb7b4-f2b2-4040-b896-da107f1a641f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='Notes']</value>
      <webElementGuid>bffa8c74-414c-4275-b50e-03d3f1fe0806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmDashboard.addReminderForm']/div[3]/textarea</value>
      <webElementGuid>298ba82c-da34-4d6d-8986-df8ec7714132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>83cc2d0e-5d0e-454f-a510-3d8d9749f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Notes' and @name = 'Notes']</value>
      <webElementGuid>db31f2de-1fed-4975-9408-280b6f3507cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
