<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_today_fc-icon fc-icon-right-single-arrow</name>
   <tag></tag>
   <elementGuidId>e3f2f204-9375-4907-a1f4-2317e3ce551d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fc-icon.fc-icon-right-single-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99cd001b-9096-4c30-bbb6-7e9029e90535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-icon fc-icon-right-single-arrow</value>
      <webElementGuid>6b06da5e-4b2e-4b1e-9c56-6d579f14dc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;manage_partner lato_font common_content ng-scope&quot;]/div[@class=&quot;container-fluid m-b-20&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;calendar dash_cal_new ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope fc fc-unthemed fc-ltr&quot;]/div[@class=&quot;fc-toolbar fc-header-toolbar&quot;]/div[@class=&quot;fc-right&quot;]/div[@class=&quot;fc-button-group&quot;]/button[@class=&quot;fc-next-button fc-button fc-state-default fc-corner-right fc-state-hover&quot;]/span[@class=&quot;fc-icon fc-icon-right-single-arrow&quot;]</value>
      <webElementGuid>a1a5fb0b-d553-49a7-a371-566ef2b33678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>68654622-80f8-4dd6-8d67-e6bb7d432d45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
