<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Onboarding</name>
   <tag></tag>
   <elementGuidId>25f05c78-e1eb-4f0a-ae36-c8e9cb754980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.open_manage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a82fa1cb-8bb4-43de-aca6-9a81ea15f5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Neighbourhood') || isActive('/AddNeighbourhood') || isActive('/Worksite') || isActive('/AddWorksite') || isActive('/AddHousing') || isActive('/Housing') || isActive('/Partner') || isActive('/Participant') || isActive('/Employer') || isActive('/AddEmployer') || isActive('/EmployerForm') || isActive('/Staff') || isActive('/AddStaff') || isActive('/Participant') || isActive('/AddParticipant') || isActive('/SelfFundedForm') || (loggedUserType === 'Partner' &amp;&amp; isActive('/Staff')) || (loggedUserType === 'Partner' &amp;&amp; isActive('/AddStaff'))) &amp;&amp; OnboardingHeaderActive)}</value>
      <webElementGuid>bf73d652-12ed-4d46-b43e-edd0e6cabf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>564e2944-d320-4a98-bd97-7fcf9a59809d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open_manage</value>
      <webElementGuid>e93076ee-ab5e-46c4-8e8c-7791ee3e9e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onboarding</value>
      <webElementGuid>60ef0066-ba59-41d1-b594-77098a1f8cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/section[@class=&quot;bs-docs-nav navbar navbar-static-top nomargin manage_partner bb- ng-scope&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-left right_nav m-l-20 ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;open_manage&quot;]</value>
      <webElementGuid>45947ab1-0e04-4974-b741-81efc4dff96c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      <webElementGuid>24ff156d-4876-4156-9d43-b29f2b43b776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Onboarding')]</value>
      <webElementGuid>70f7e991-039a-4558-9c16-ea92ae07b8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>9589c771-100f-4150-943e-04dd315642ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positions'])[1]/preceding::a[1]</value>
      <webElementGuid>601ed2fd-09b8-4067-94cf-163356d672b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::a[2]</value>
      <webElementGuid>ef5c9821-be89-4886-bccb-34fdc4a307b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Onboarding']/parent::*</value>
      <webElementGuid>ddd1bc7a-d048-43a3-adc4-16f32a84a216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>1957fe0c-dc32-4fe1-8c3f-0b8e357821f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>20207016-9ee8-4a11-a823-b47fee4f00eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Onboarding' or . = 'Onboarding')]</value>
      <webElementGuid>9db69c6e-2364-41c6-8b3f-641301a263d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
