<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Onboarding</name>
   <tag></tag>
   <elementGuidId>f1147887-bcce-4190-b0e1-6b7ef81d0dc6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0)' and (text() = 'Onboarding' or . = 'Onboarding')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.open_manage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>468bbaed-31f1-4dbd-8017-d50121ab1abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Neighbourhood') || isActive('/AddNeighbourhood') || isActive('/Worksite') || isActive('/AddWorksite') || isActive('/AddHousing') || isActive('/Housing') || isActive('/Partner') || isActive('/Participant') || isActive('/Employer') || isActive('/AddEmployer') || isActive('/EmployerForm') || isActive('/Staff') || isActive('/AddStaff') || isActive('/Participant') || isActive('/AddParticipant') || isActive('/SelfFundedForm') || (loggedUserType === 'Partner' &amp;&amp; isActive('/Staff')) || (loggedUserType === 'Partner' &amp;&amp; isActive('/AddStaff'))) &amp;&amp; OnboardingHeaderActive)}</value>
      <webElementGuid>a1529444-d29e-4a93-b8ef-25c17ad7011b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>77695525-5348-4132-a672-720510702ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open_manage</value>
      <webElementGuid>b833a134-ba4b-4be4-9ffd-258c351d49d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onboarding</value>
      <webElementGuid>f1bd13cc-39e0-4bcc-9743-30230771de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/section[@class=&quot;bs-docs-nav navbar navbar-static-top nomargin manage_partner bb- ng-scope&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-left right_nav m-l-20 ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;open_manage&quot;]</value>
      <webElementGuid>caa1ffcb-3c9b-4d7c-b289-cfe85616aa94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      <webElementGuid>23882e03-cabc-44d2-9d19-ba0264b98a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Onboarding')]</value>
      <webElementGuid>24261a9f-6f54-4333-a47c-4868cae310b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>49dc0ea3-5fcb-46fe-b5ee-97a3cd72270c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positions'])[1]/preceding::a[1]</value>
      <webElementGuid>b49db686-fbfa-48cf-b152-06a0c09a6b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contracts'])[1]/preceding::a[2]</value>
      <webElementGuid>3a56e794-b5b2-4cdb-8ab0-83f7c26a265d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Onboarding']/parent::*</value>
      <webElementGuid>72822c9f-ac5e-44b7-a0cc-3d5623b2ffc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>bbf08f70-be7b-4ff1-8e8c-7c0c9a6b87cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>2b1fa251-ccbb-49be-8e45-ac5425c99932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Onboarding' or . = 'Onboarding')]</value>
      <webElementGuid>2debab1f-7d33-4d6d-9ccf-cb80c0772033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
