<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel</name>
   <tag></tag>
   <elementGuidId>2959ee9d-3eb3-4cf5-b168-2b3bc6879f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Cancel&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Cancel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb3f83d0-5cc2-4449-a377-64b74ee4d1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctt custom-del</value>
      <webElementGuid>db6df289-ff2b-4805-b07d-e0c44df43195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>closePopup()</value>
      <webElementGuid>446fff3d-e586-4a7e-a920-bcbe82cb3987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>35303910-1df0-4da4-b8f8-9386e0d9d132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Cancel</value>
      <webElementGuid>38acebdd-fc38-424a-8275-389c7e860bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 text-align-center m-t-15&quot;]/a[@class=&quot;ctt custom-del&quot;]</value>
      <webElementGuid>13d2ebf3-5880-4391-9875-a8107e18f027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Cancel']</value>
      <webElementGuid>b1a0e9aa-460d-4e57-8801-e848a45813a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[4]/a[2]</value>
      <webElementGuid>93ebaec7-2d02-4b4c-8a63-4ca5827354c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel')]</value>
      <webElementGuid>bb149ffa-eaca-429d-a9c9-58976da2a98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::a[1]</value>
      <webElementGuid>3a29d41c-5ca6-42b3-a48a-8e697574c15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time limit not correct'])[1]/following::a[2]</value>
      <webElementGuid>d3423723-1b9a-4451-b746-1eac6e75b555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>a59fce32-c175-4317-adf6-fd442e745b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>8553376c-d5d4-4b19-a75b-ef1c5a6c94f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Cancel' and (text() = '  Cancel' or . = '  Cancel')]</value>
      <webElementGuid>f617b7db-e2b8-4460-bd50-7e78e9b521e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
