<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Participants</name>
   <tag></tag>
   <elementGuidId>c32ee23e-8006-41e7-aad4-8676a394525c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav.navbar-right.col-md-push-3.ng-scope > li.ng-scope > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='bs-navbar']/ul/li[2]/a)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f542556-8bf1-492b-a286-e6e0bb0a344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Participant') || isActive('/AddParticipant') || isActive('/SelfFundedForm')) &amp;&amp; OnboardingParticipantActive)}</value>
      <webElementGuid>f3517465-66cb-4894-ad06-7ede03b1490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Participant</value>
      <webElementGuid>683c002b-0391-4c5b-a613-9018183f9450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Participants</value>
      <webElementGuid>4fb33e3b-8786-4885-86c1-2025f117ccfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/div[@class=&quot;col-xs-12 ng-scope&quot;]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-right col-md-push-3 ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]</value>
      <webElementGuid>7f8b1e65-1c62-4550-a096-f8e5b90b999f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='bs-navbar']/ul/li[2]/a)[3]</value>
      <webElementGuid>0f5dc7ca-1e54-44ae-90df-a8458dd35760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Participants')]</value>
      <webElementGuid>eff8e5d0-c735-4909-ad2d-be5edc81d323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/following::a[1]</value>
      <webElementGuid>f1b134b1-c346-49e2-8db7-37a1e733b879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optisol Admin'])[1]/following::a[3]</value>
      <webElementGuid>a020a6aa-df32-4c31-a4a5-abcfcdb6533f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/preceding::a[1]</value>
      <webElementGuid>d3fbbbdc-40de-4b16-abf3-8a3c4dd5b3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[1]/preceding::a[2]</value>
      <webElementGuid>7339f19d-48dc-4083-88f1-f326a44b9167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Participants']/parent::*</value>
      <webElementGuid>e2b96010-69d8-4ae6-9477-bc3c0fde7156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/Participant')]</value>
      <webElementGuid>a7d26276-f531-41f4-9739-a85a4ca576c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/ul/li[2]/a</value>
      <webElementGuid>99798ee8-8b17-4396-b979-9c089394b5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Participant' and (text() = 'Participants' or . = 'Participants')]</value>
      <webElementGuid>6ebccf64-5be8-498b-8d2b-db627eb471af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
