<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>df7835e1-7663-4c02-b207-46fdf22541ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmDashboard.addReminderForm']/div[4]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.help_btn.back_minwdth.float-right.fs-12.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a59608a-887d-4f4a-bf15-c3357669e888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn help_btn back_minwdth float-right fs-12 ng-scope</value>
      <webElementGuid>fd24385f-66ca-43b4-97df-10b8637f980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vmDashboard.ReminderLoading</value>
      <webElementGuid>1b379fea-f542-4f7e-9672-5eeff3c2249c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmDashboard.SaveReminder(vmDashboard.addReminderForm.$valid)</value>
      <webElementGuid>ef6423c8-afd1-4947-832c-f516f7ba0998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>b5ca3303-d654-42c7-b6c8-d8a584a56339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmDashboard.addReminderForm&quot;)/div[@class=&quot;clearfix col-xs-12 cal_div&quot;]/button[@class=&quot;btn help_btn back_minwdth float-right fs-12 ng-scope&quot;]</value>
      <webElementGuid>d4cac94e-0223-44f0-bd99-024715778980</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmDashboard.addReminderForm']/div[4]/button[2]</value>
      <webElementGuid>73f1bc00-930d-456a-907d-d44a542c3cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discard'])[1]/following::button[1]</value>
      <webElementGuid>9adbb4d0-66b7-449c-9cfd-178f98a8d31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Reminder'])[1]/following::button[3]</value>
      <webElementGuid>ed29073f-a483-4f98-8913-60f0d113bef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='oneworlddemo@yopmail.com'])[1]/preceding::button[1]</value>
      <webElementGuid>3cf40fb7-9b34-4b96-9e7f-bbe94ddf121b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>85d4d649-941e-47fe-abe6-a391da0ac93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>a136fcda-9782-4d4a-897d-71c0dc8ba87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>202d52c1-596a-40d9-ad5d-ce5d1e7e5688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
