<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Required</name>
   <tag></tag>
   <elementGuidId>b28dd5f9-dbf1-4f02-913b-547d9adf2eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmDashboard.addReminderForm']/div/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.errormsg.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>037c4d3c-b4db-4066-8849-8b2212b35454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errormsg ng-scope</value>
      <webElementGuid>4b86a510-de1e-44b8-9fe8-8a08c9cd507b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vmDashboard.addReminderForm.Title.$error.required</value>
      <webElementGuid>7fea421f-cb3a-48d3-9862-7304f7cff553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>1494f0d0-20fa-4dc8-ba36-8a355671178c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmDashboard.addReminderForm&quot;)/div[@class=&quot;col-xs-12 m-t-15 nopadding&quot;]/div[@class=&quot;col-xs-12 p-0&quot;]/span[@class=&quot;ng-scope&quot;]/span[@class=&quot;errormsg ng-scope&quot;]</value>
      <webElementGuid>3ca5cf71-9f32-437b-bf2a-f293c934f1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmDashboard.addReminderForm']/div/div/span/span</value>
      <webElementGuid>b715642b-e3ee-4bf6-89fc-4ca02499374a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Reminder'])[1]/following::span[2]</value>
      <webElementGuid>6e63499d-f158-4e7d-81a7-e23c29540926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ticket'])[1]/following::span[2]</value>
      <webElementGuid>2adcbef4-6a90-4f91-9c68-0036117ea796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/preceding::span[2]</value>
      <webElementGuid>21611b8a-2f3f-456c-a6c4-b0f9f18e2f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[3]/preceding::span[4]</value>
      <webElementGuid>217e3270-85bf-42c2-ab01-f992ea12372a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Required']/parent::*</value>
      <webElementGuid>48e80438-8e4c-4400-a36b-4a3ab1b3752b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/span/span</value>
      <webElementGuid>738b1627-8513-4385-845f-e6679b43950f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>e9a9a55e-6827-4dce-b5c7-f6cdea5f9936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
