<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_participant1393</name>
   <tag></tag>
   <elementGuidId>3454bd62-e2a0-43fb-b890-3eedc903f05d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#participant1393</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='participant1393']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c5542df-6fe7-44bf-90cd-bfbb72730ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>456813eb-14c4-4244-9ab2-d65258bc5747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>participant1393</value>
      <webElementGuid>b1a9c3b6-175e-4167-b47d-6bb9ffc77c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>participant1393</value>
      <webElementGuid>8905e3b8-5fe8-44bd-9c1d-2ad0defc4a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.pushSelectedIds(participant.UserId)</value>
      <webElementGuid>65e28fa1-ddeb-4e1c-8f0b-abbb318e3a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;participant1393&quot;)</value>
      <webElementGuid>658ff11c-2193-46cd-ab35-04c69bee3bcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='participant1393']</value>
      <webElementGuid>e2d19911-5857-4424-b49a-d835e6b8d691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>dd281c5c-b77f-4d38-bf72-25173888b493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'participant1393' and @id = 'participant1393']</value>
      <webElementGuid>d691ccd1-0d53-4ecc-940d-84d1cf5a4340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
