<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>3ce061b3-8f90-4834-9dbe-e551717c0d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-caredesk.fs-12.pointer.ml-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ticket_notes']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3f1e51f-c80c-41da-911e-a01232b104d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-caredesk fs-12 pointer ml-0</value>
      <webElementGuid>5ffab58a-1648-4818-a60a-da18a6b01741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmTicket.AddNotes(listIndex)</value>
      <webElementGuid>e1b7ee9a-f601-408a-9f27-5f7aa9d89c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>acb71b1b-d669-4af1-9405-30bfd3f05d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ticket_notes&quot;)/div[@class=&quot;row m-t-20&quot;]/div[@class=&quot;m-t-15 col-sm-4 p-0 text-center m-b-20 ng-scope&quot;]/button[@class=&quot;btn btn-caredesk fs-12 pointer ml-0&quot;]</value>
      <webElementGuid>e359ca58-b083-45ec-8321-09c858327283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ticket_notes']/div/div[2]/button</value>
      <webElementGuid>bd46c1a5-5ecd-4f76-9613-f59f5eb3dbf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/following::button[1]</value>
      <webElementGuid>3c606f48-46f6-4b88-9501-34ea278026fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[2]/preceding::button[1]</value>
      <webElementGuid>e8b6f8e2-172e-4106-be9b-81376e2c0a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>40214ad6-c14f-4e4c-b527-09c126ca2987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cbc18d7f-40ba-46f2-bb76-c1b65efa5cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>50b33ba0-f189-49ce-b830-cee8b308afe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
