<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em__fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>052a3ad1-7185-4407-ac98-d3847ab886b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmTicket.RaiseTicketForm']/div/div/div/div[4]/div[2]/div[2]/div/span/button/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>fb4ed8de-feb3-4f35-a354-9f4894a4d84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>224090f8-03d2-4c0b-8a45-a943826a210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ff466cd-b704-4cec-adfe-63a0612ca1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmTicket.RaiseTicketForm&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row m-t-15 m-l-10&quot;]/div[@class=&quot;col-md-8 bg-white br5px m-l-0 br-gray&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 m-t-10 nopadding m-b-35 ng-scope&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;position-relative&quot;]/span[@class=&quot;input-group-btn scope-calen-icon&quot;]/button[@class=&quot;btn btn-default py5&quot;]/em[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>69d311c0-7e17-4c24-8aeb-ad8d332656e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmTicket.RaiseTicketForm']/div/div/div/div[4]/div[2]/div[2]/div/span/button/em</value>
      <webElementGuid>7fd555ff-a5e3-46eb-a703-f0881f604682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>66870007-bd9e-4eb0-9d73-8a7473387507</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
