<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em__fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>4c038696-7f31-4dd8-9e83-58195890cb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmTicket.RaiseTicketForm']/div/div/div/div[4]/div[2]/div[2]/div/span/button/em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>3f6536d6-9bac-4f75-ba34-311cf25529e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>d984493b-040a-479b-99fa-f5f25f1a6ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0d3d269-70ff-4fe2-b6b7-67d3c1760863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmTicket.RaiseTicketForm&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row m-t-15 m-l-10&quot;]/div[@class=&quot;col-md-8 bg-white br5px m-l-0 br-gray&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 m-t-10 nopadding m-b-35 ng-scope&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;position-relative&quot;]/span[@class=&quot;input-group-btn scope-calen-icon&quot;]/button[@class=&quot;btn btn-default py5&quot;]/em[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>27d2550a-ac63-485b-8dad-90983d0f1a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmTicket.RaiseTicketForm']/div/div/div/div[4]/div[2]/div[2]/div/span/button/em</value>
      <webElementGuid>84ef991a-1728-4716-bf49-712858d8f961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>00016dec-7206-49dc-9229-24a0bf2ae7a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
