<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select an option--                _c26f14</name>
   <tag></tag>
   <elementGuidId>496b9055-dd42-4cd0-b238-718d3dd6dc99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Severity&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Severity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>217ace01-1171-4f78-9f98-6fdb4b5a4290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control m-b-10 ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>09f40f66-d3fa-4b83-87d9-d71bfe388a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Severity</value>
      <webElementGuid>d94fb9b6-89c0-4438-9f31-4b65a9050ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmTicket.TicketFormData.Severity</value>
      <webElementGuid>320de566-0df0-40e9-9ea4-7f2f74402b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(vmTicket.TicketFormData.StatusName &amp;&amp; vmTicket.TicketFormData.StatusName != 'New' &amp;&amp; !vmTicket.isAdd) || loggedUserType === 'Partner'</value>
      <webElementGuid>8c25ef0d-4b1b-402b-9409-76a54457028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                --Select an option--
                                                CriticalHighNormal
                                            </value>
      <webElementGuid>b11cd5fc-789d-4735-a140-0d43715e9cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmTicket.RaiseTicketForm&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row m-t-15 m-l-10&quot;]/div[@class=&quot;col-md-8 bg-white br5px m-l-0 br-gray&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12 m-t-10 nopadding ng-scope&quot;]/div[@class=&quot;col-xs-12&quot;]/select[@class=&quot;minimal form-control m-b-10 ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>59858c70-e9b4-4278-acc6-f0d1c80ea384</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Severity']</value>
      <webElementGuid>68a0bd8c-6045-42eb-8580-fe83b0c4379a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmTicket.RaiseTicketForm']/div/div/div/div[2]/div/div/select</value>
      <webElementGuid>266355b6-fd34-4f0d-b8dc-a4edef1058fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>df1ac195-4634-4722-9466-f83b7527659b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>e3560139-1750-4152-9a29-e9c1373b862a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>5a006d29-b20f-49c1-a42f-8965bac23ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Severity' and (text() = '
                                                --Select an option--
                                                CriticalHighNormal
                                            ' or . = '
                                                --Select an option--
                                                CriticalHighNormal
                                            ')]</value>
      <webElementGuid>ba1ee47d-c7b8-4490-a31f-5cc81ac7c7cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
