<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Option                              _264d98_1</name>
   <tag></tag>
   <elementGuidId>01727ac2-bed8-4fd3-87dd-acc82ce2b585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;EndMeridiem&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='EndMeridiem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>861731f1-b85e-4adb-828e-cc22a79b351b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>80fbed5d-5436-4afd-b4d9-3865f5f0d1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EndMeridiem</value>
      <webElementGuid>283e5857-0087-4617-8193-1c50e4262930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.EndMeridiem</value>
      <webElementGuid>ef9152dc-5b1e-4c76-acb9-74539537626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>e6a09917-6ff3-476e-b48a-b1e86d128c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Option
                                    AM
                                    PM
                                </value>
      <webElementGuid>97f05972-afa2-4bb7-8412-0cde0c202cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 nopadding&quot;]/select[@class=&quot;minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>6ed43d1a-35bd-40ff-ab66-3a4ec346372f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='EndMeridiem']</value>
      <webElementGuid>804d62d4-5aa7-41a5-9492-729c3532d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div[2]/div[2]/select</value>
      <webElementGuid>d8b0673c-7e83-4ca2-9548-ccd78cd6f22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::select[2]</value>
      <webElementGuid>a6b34134-afd5-4896-97ce-bc997a24c8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[4]</value>
      <webElementGuid>72c80f79-eb7d-49a3-8d0d-95b03f538722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>9cbd68b2-a040-4082-83fc-110a4182536c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>982d9dc6-b76b-45b7-a13a-3b58154adb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/select</value>
      <webElementGuid>fa72d676-e064-4161-940b-efa94e66e369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'EndMeridiem' and (text() = '
                                    Option
                                    AM
                                    PM
                                ' or . = '
                                    Option
                                    AM
                                    PM
                                ')]</value>
      <webElementGuid>9ac9a213-047c-4f0e-a873-c77029a7e4af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
