<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Time                                _48fbf9_1</name>
   <tag></tag>
   <elementGuidId>a6860868-144f-487f-9976-5641190bd726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;EndTime&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='EndTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8841797e-d2d9-4cea-9c0a-0a2621847db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-touched ng-dirty ng-valid-parse ng-valid-required ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>786dbc44-deb2-4c30-a3d0-9f0f41d1f666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EndTime</value>
      <webElementGuid>40016a8e-e114-4b88-b56f-f151f121a297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.EndTime</value>
      <webElementGuid>20f183e6-83e0-4904-b195-2f8dc680dca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>bc98bbd8-2042-4a23-9611-9ebd93cdefd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                </value>
      <webElementGuid>c57fd12c-d6e0-4bc0-8483-d583967c66fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 p-l-0&quot;]/select[@class=&quot;minimal form-control ng-touched ng-dirty ng-valid-parse ng-valid-required ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>f8648280-7b7c-4950-8e86-60176771da94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='EndTime']</value>
      <webElementGuid>36c2bd06-8a04-495a-8687-37ec79a3f18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div[2]/div/select</value>
      <webElementGuid>06d589da-5490-4e26-a599-964826b2c38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::select[1]</value>
      <webElementGuid>2e8723bc-3e1e-403a-94ea-c4e7a9bdda26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[3]</value>
      <webElementGuid>88303412-ee3a-488f-9ba7-efe561a190d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>3d387b65-e15c-4628-96a1-2f9eb3326a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/preceding::select[2]</value>
      <webElementGuid>e926e046-c644-40b2-b895-5f332609d104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>5351622e-2c4c-4ca2-a4e0-97e09895d6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'EndTime' and (text() = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ' or . = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ')]</value>
      <webElementGuid>4c2b2abd-e2e5-421e-90ec-9b7d28c3dd0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
