<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Time                                _48fbf9</name>
   <tag></tag>
   <elementGuidId>17d7fbca-74c0-4227-ae4a-4494497f2691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;StartTime&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='StartTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff294031-6c9b-420f-b202-1310a36c115a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-touched ng-dirty ng-valid-required ng-valid-parse ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>531981be-51dc-45b4-baa3-d7483a50f4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartTime</value>
      <webElementGuid>d4c3b711-a158-4ff0-bd8d-7fbc8609cbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vmSlot.addSlotData.StartTime</value>
      <webElementGuid>806054c3-ec28-4dcd-951e-069c0923a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmSlot.fnTimeValidation()</value>
      <webElementGuid>cb7d1d55-572c-4e31-a245-602dfb8d877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                </value>
      <webElementGuid>b04af0b1-7c15-48fb-b110-4dfe56a4008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12 m-t-15&quot;]/div[@class=&quot;col-md-5 nopadding&quot;]/div[@class=&quot;col-md-6 p-l-0&quot;]/select[@class=&quot;minimal form-control ng-touched ng-dirty ng-valid-required ng-valid-parse ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>9249e171-3105-4263-8bf6-bd292ec25803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='StartTime']</value>
      <webElementGuid>149a8ef4-25a1-4253-8850-93e496cb2f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[3]/div/div/select</value>
      <webElementGuid>eb55af73-5df2-4bd9-967c-c11ace7834d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>4ea60b8d-97c3-4420-8583-7eb6bde5a938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/preceding::select[1]</value>
      <webElementGuid>f6ba911f-0b49-4dad-a91d-0ad19073afab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/preceding::select[2]</value>
      <webElementGuid>fd393040-7563-4422-a2e8-032152e23423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/div/div/select</value>
      <webElementGuid>a7248489-fb99-47c3-824d-e28ab3db587c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'StartTime' and (text() = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ' or . = '
                                    Time
                                    00:00
                                    01:00
                                    02:00
                                    03:00
                                    04:00
                                    05:00
                                    06:00
                                    07:00
                                    08:00
                                    09:00
                                    10:00
                                    11:00
                                ')]</value>
      <webElementGuid>d72c4564-4da2-4548-b37e-fc391e213b98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
