<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Required</name>
   <tag></tag>
   <elementGuidId>606f9b2b-b263-441a-bfbe-b29e0214d4e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.errormsg.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmSlot.addSlotForm']/div[2]/div/div/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>190463fe-bece-4581-82e8-e87fe4a55466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errormsg ng-scope</value>
      <webElementGuid>fef290f2-2c77-4c95-ad0f-d5c12673e5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vmSlot.addSlotForm.ScheduleDate.$error.required</value>
      <webElementGuid>76a0df78-a4c3-4738-b5d2-85785f6dcea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>0dc5b3d7-e403-4226-96d9-7d3b204376de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.addSlotForm&quot;)/div[@class=&quot;col-xs-12  m-t-15&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-6 custom_date&quot;]/span[@class=&quot;ng-scope&quot;]/span[@class=&quot;errormsg ng-scope&quot;]</value>
      <webElementGuid>af83ad83-85a4-4fab-a2d4-f9e0fb6cfeee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.addSlotForm']/div[2]/div/div/span/span</value>
      <webElementGuid>8f643ecd-19f7-44b6-a4d5-0fe116a15d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::span[2]</value>
      <webElementGuid>5ad7efa5-5041-465b-bb32-26b3052b5f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[1]</value>
      <webElementGuid>2727c355-52e9-49ef-ac4b-afff5520c0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Required']/parent::*</value>
      <webElementGuid>a9566c80-4ec6-44a8-937e-7092d51c4142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>35d90d28-c3bd-4a69-a860-0551ad014683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>b80626f0-4bf0-4e4a-920c-3f2830ab6333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
