<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Partners</name>
   <tag></tag>
   <elementGuidId>eba6ab0b-701b-4b9b-9752-0eafaa2aeaa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='bs-navbar']/ul/li/a)[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav.navbar-right.col-md-push-3.ng-scope > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8c112982-e992-4aa3-8350-9bd8ce0d7611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Partner') || isActive('/createPartner')) &amp;&amp; OnboardingPartnerActive)}</value>
      <webElementGuid>f39f7157-4ad6-496e-9ec7-7005326afe21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Partner</value>
      <webElementGuid>0ab1b5ba-0157-43c6-98a4-62100afd0293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Partners</value>
      <webElementGuid>6d5a3bc5-ef94-4016-bf6f-1c503b61ddb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/div[@class=&quot;col-xs-12 ng-scope&quot;]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-right col-md-push-3 ng-scope&quot;]/li[1]/a[1]</value>
      <webElementGuid>16f37ab3-71ca-4059-988d-bdcae9aa6146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='bs-navbar']/ul/li/a)[12]</value>
      <webElementGuid>069e2546-635f-4961-bae4-a77a6b528896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Partners')]</value>
      <webElementGuid>7cf4068c-0833-4e08-b846-f152528d2825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Optisol Admin'])[1]/following::a[2]</value>
      <webElementGuid>1488b61b-bb59-490e-b020-90d6b6c1ff7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/following::a[4]</value>
      <webElementGuid>d63f6bc1-d070-4161-af2d-ed97d1900f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[1]/preceding::a[1]</value>
      <webElementGuid>ade40ea4-3437-4843-b507-6d79cb49d700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/preceding::a[2]</value>
      <webElementGuid>605a4aba-f8f2-4614-851f-5e10f9ecad9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Partners']/parent::*</value>
      <webElementGuid>5f0f93c4-4f31-4741-82a3-7aab7c6c539e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/Partner')])[2]</value>
      <webElementGuid>47bf8ee2-6d53-4dbc-998e-ccadab8f252b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/ul/li/a</value>
      <webElementGuid>18913201-692b-4290-9ac7-83062eaffa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Partner' and (text() = 'Partners' or . = 'Partners')]</value>
      <webElementGuid>8a220b18-353f-42a0-b097-88245202977f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
