<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>a03d2275-2822-4d6f-a200-58c07d208228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link-color-blue.fs-12.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'View')])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>91ed06de-b83d-403a-97c4-ddfcbef0e228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-color-blue fs-12 ng-scope</value>
      <webElementGuid>31cc6b49-1cbc-488a-8de7-850a6deebd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>participant.ArrivedOn != null</value>
      <webElementGuid>04e12578-766b-4d2f-881c-55c10f71a1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmPlacemetTracker.openPreview(vmPlacemetTracker.PostPlacementConfigArrivalCheckinType,participant.UserId)</value>
      <webElementGuid>81296ffa-0b74-46a5-a9c5-df4f183db117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>ade393ee-91f3-4c12-bdef-ff3142b3196b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-0 ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;container-fluid ng-scope&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;part-tracker-container bg-white&quot;]/div[@class=&quot;row m-l-0 m-r-0 p-t-15&quot;]/div[@class=&quot;col-lg-4 col-md-4 col-sm-12 text-align-center participant-tracker-lists br-left-gray h80px&quot;]/div[@class=&quot;pl_t_arrival_guide pl_track_bottom&quot;]/div[@class=&quot;pl_guide_right m-l-20&quot;]/h5[@class=&quot;m-0 text-black text-align-left&quot;]/a[@class=&quot;link-color-blue fs-12 ng-scope&quot;]</value>
      <webElementGuid>1eeb1e06-f343-4e53-bfbc-c2b9f3ea389b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[4]</value>
      <webElementGuid>8dc8980b-fd6a-4cf0-8672-53591952b364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/following::a[1]</value>
      <webElementGuid>f1addee1-119a-4395-a346-fcf755ba2094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arrived on 06/12/2023'])[1]/preceding::a[1]</value>
      <webElementGuid>f6c1b662-ced8-47fc-97b6-4c19520f1bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Yet Verified'])[1]/preceding::a[1]</value>
      <webElementGuid>4b1998e5-4d2c-42f2-b914-4d28589f570f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[31]</value>
      <webElementGuid>0c7e48f1-2783-4fb0-b5e3-23af31353726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/a</value>
      <webElementGuid>0442b023-9022-4c27-8533-211183088498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'View' or . = 'View')]</value>
      <webElementGuid>93c9c25a-2f68-42dc-b49f-26d93a26891c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'View')])[12]</value>
      <webElementGuid>3f53dbcb-2e91-4277-a853-c3f3199ace4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Signed DS7002'])[2]/following::a[1]</value>
      <webElementGuid>f5a8408d-8605-481b-b28e-646fb79ef565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Profile'])[3]/preceding::a[1]</value>
      <webElementGuid>deadbb27-2160-4893-86bb-16cfeec7cf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participant ID'])[3]/preceding::a[2]</value>
      <webElementGuid>e14dd657-c6d3-43af-bcbc-03edf65ae345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[45]</value>
      <webElementGuid>ca7a89d2-1aba-4f0b-beb0-ffed453cdb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h5/a</value>
      <webElementGuid>f6ee3593-6b9d-4ee4-9998-4e0bef56f301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
