<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Yes</name>
   <tag></tag>
   <elementGuidId>cda697ef-8b36-4754-b6d2-3ea4d3a92103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Yes&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db166a3d-8c3a-46cd-b9af-063a9f4ea048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-create ctt ng-scope</value>
      <webElementGuid>91c14104-1214-4714-b92e-5e335df422ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!vmParticipant.isMovetoArchive</value>
      <webElementGuid>92183761-87e0-4ca8-977e-143678054ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.moveToUnArchive()</value>
      <webElementGuid>4b5f50ab-4df7-4ba8-85f6-f878b9856ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>5a940735-ab79-4df7-ad7b-8a303544f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>8f85f274-7d2b-4f94-afa0-d5abab9655bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade ng-isolate-scope in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;forumpopup  approvals-block-popup-11 dialog-popup ng-scope&quot;]/div[@class=&quot;modal-body clearfix&quot;]/div[2]/a[@class=&quot;custom-create ctt ng-scope&quot;]</value>
      <webElementGuid>cff3acfa-15c3-4a0f-a1de-2837adcf207b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Yes']</value>
      <webElementGuid>eeedc31d-a171-498a-bb7b-708ea0bfeaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Yes')]</value>
      <webElementGuid>e0feca05-4a10-4f10-bc3c-4790300eff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to move selected Participant(s) from Archive?'])[1]/following::a[1]</value>
      <webElementGuid>87aa7161-2eb0-481b-af0e-6e5e5c103753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM'])[1]/following::a[1]</value>
      <webElementGuid>29ca6362-0758-4b45-ab2e-587551423d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[1]</value>
      <webElementGuid>e42fdcc6-2d0f-4ac8-bf6d-8be20dbd25d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>dab84b2b-3edd-4d8b-bc13-b1e997ed15af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>0631c61b-5f70-405b-af87-c2921d478b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Yes' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>f7ed7f5d-2570-4076-bedc-c699fc5421b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
