<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New_206</name>
   <tag></tag>
   <elementGuidId>456434a0-27ee-40c5-b5d2-05ab195accc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;206&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='206']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9597a68-e1be-475e-b85f-9dd78b897aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6c60c838-7586-41f8-a73f-3f100213b491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Deleted</value>
      <webElementGuid>b7f30524-08e2-4f49-b2d6-50762ae44f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmParticipant.FilterStatus</value>
      <webElementGuid>8d669492-ef4c-4ceb-96c8-16969d30a8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.FilterPendingStatus(status)</value>
      <webElementGuid>cfef6fca-a610-4adb-8417-9ddf6395faf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-4 ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>c0ab0824-fcb5-4257-89e4-ba78a43e5ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>206</value>
      <webElementGuid>48f58d9c-d4c4-43a1-86e7-ab7ef4d55e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;participant_grid_checklist&quot;]/div[@class=&quot;ng-scope col-md-7&quot;]/div[@class=&quot;showingresult text-align-right&quot;]/div[@class=&quot;r_checklist&quot;]/label[@class=&quot;ng-scope&quot;]/input[@class=&quot;m-t-4 ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>cf017607-c500-410f-bfc7-b001d9932635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='206']</value>
      <webElementGuid>0042444b-e947-47da-a991-c9bdb674ecce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[6]/input</value>
      <webElementGuid>1c9d92e0-fc47-475b-a54b-9e56d55f7bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = '206']</value>
      <webElementGuid>41df103f-7615-4467-90a2-24a6a9381e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
