<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Placed_196</name>
   <tag></tag>
   <elementGuidId>05f31130-1667-48dd-993c-abf3b5bb3c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;196&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='196']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>474470c5-1370-4d89-8f1e-ecc4b7b11553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9fecf25d-d0dc-4e07-9795-72f279e48c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>41967951-bdc0-4ba1-a763-f8bcd9660e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmParticipant.FilterStatus</value>
      <webElementGuid>5e4b1044-2510-4346-a312-b2210c90b8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.FilterPendingStatus(status)</value>
      <webElementGuid>7319566d-8084-4b6c-ad76-16aa6abd5978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-4 ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>ee39cacc-311c-429c-89bf-0490f8cc2ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>196</value>
      <webElementGuid>1a9d49e4-15fb-4bab-b085-8e7218e34723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;participant_grid_checklist&quot;]/div[@class=&quot;ng-scope col-md-6&quot;]/div[@class=&quot;showingresult text-align-right&quot;]/div[@class=&quot;r_checklist&quot;]/label[@class=&quot;ng-scope&quot;]/input[@class=&quot;m-t-4 ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>2976286a-07a7-4357-ab40-a301cbb62b25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='196']</value>
      <webElementGuid>e40396e7-69c2-4b7c-9cf8-9dd99148e027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>c7edc550-cd13-480f-b43c-3dd4f5019060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = '196']</value>
      <webElementGuid>8fca4f59-ae31-4945-9707-5d573b1124a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
