<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Employers</name>
   <tag></tag>
   <elementGuidId>25cc4f07-3413-4aed-a3aa-ed4aed188521</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='bs-navbar']/ul/li[3]/a)[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.navbar-nav.navbar-right.col-md-push-3.ng-scope > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b63f25d-5073-4203-b21f-daa9e39cc5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Employer') || isActive('/AddEmployer') || isActive('/EmployerForm')) &amp;&amp; OnboardingEmployerActive)}</value>
      <webElementGuid>9a145613-0e74-417f-b2c3-7d5e1ba3ce62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Employer</value>
      <webElementGuid>20931f59-c252-4b45-8533-b3684cc94c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employers</value>
      <webElementGuid>ff5aaaa1-91a8-4f83-ac5e-167d8c22f7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/div[@class=&quot;col-xs-12 ng-scope&quot;]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-right col-md-push-3 ng-scope&quot;]/li[3]/a[1]</value>
      <webElementGuid>7e82c654-0f50-4281-afd3-bfcd9e1f5de0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='bs-navbar']/ul/li[3]/a)[3]</value>
      <webElementGuid>029ac7b5-9ca0-4765-8160-e4cc90b0c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employers')]</value>
      <webElementGuid>5215fac3-b183-4840-9b19-344d5fb3874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[1]/following::a[1]</value>
      <webElementGuid>a9c1ac14-b871-459a-9f85-64e19ff34fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partners'])[1]/following::a[2]</value>
      <webElementGuid>8f38fba4-567d-44cc-bb0d-564b93e85d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[1]/preceding::a[1]</value>
      <webElementGuid>3417f152-f852-4d8c-a9c4-df3ee70bbfec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Housing'])[1]/preceding::a[2]</value>
      <webElementGuid>7a71430e-d45d-4bd6-8b8f-a12011f48910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employers']/parent::*</value>
      <webElementGuid>87b40cbc-3544-46bc-93f2-3839e89bba47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/Employer')]</value>
      <webElementGuid>fd394e30-536d-4b27-bbf6-8811db9d19c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/ul/li[3]/a</value>
      <webElementGuid>afc7a001-0355-4e74-ab67-d1be9729b699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Employer' and (text() = 'Employers' or . = 'Employers')]</value>
      <webElementGuid>1c31e8e7-f1b0-4ef5-b251-d83f28f3a963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
