<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Housing</name>
   <tag></tag>
   <elementGuidId>df885391-548a-4dda-8972-ff0daffcf52f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//nav[@id='bs-navbar']/ul/li[5]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f97bf6ae-4fd9-4908-9c2c-09676e35ea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/AddHousing') || isActive('/Housing')) &amp;&amp; OnboardingHousingActive)}</value>
      <webElementGuid>a089d8cd-7c33-448a-9961-cb809dc5ae1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/Housing</value>
      <webElementGuid>67290e62-8151-4e70-8556-f8fa009356aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>06df5ef5-aab5-4101-9611-8ff0aec02c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>397a00ec-613d-4e7b-a347-83eafaec0761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Housing</value>
      <webElementGuid>18a9eb1a-a4e0-49c4-9884-78b14ed280bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/div[@class=&quot;col-xs-12 ng-scope&quot;]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-right col-md-push-3 ng-scope&quot;]/li[5]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>92c7f75d-da9f-46b4-b587-95b0b290be33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//nav[@id='bs-navbar']/ul/li[5]/a)[2]</value>
      <webElementGuid>ffe45dd6-e962-439b-9d64-b3e004cd159c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Housing')]</value>
      <webElementGuid>33569226-aef5-4264-8c9f-72f4fb4f480f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[1]/following::a[1]</value>
      <webElementGuid>638f0050-23e6-43bc-b15d-ad488a67e652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/following::a[2]</value>
      <webElementGuid>c2e41bb4-f91a-42a4-b0b1-550e2d1d37c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/preceding::a[1]</value>
      <webElementGuid>bf0cb5b4-efd0-47ae-9a67-f70148a4f3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLACED PARTICIPANTS'])[1]/preceding::a[2]</value>
      <webElementGuid>6a76667f-f617-4170-b28d-1ab4b0f80bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Housing']/parent::*</value>
      <webElementGuid>d09a2bd4-e1d2-46f6-8b2f-e64a77cbe246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/Housing')]</value>
      <webElementGuid>eae3c0eb-f1cb-4b24-b27d-e7a3dca78322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/nav/ul/li[5]/a</value>
      <webElementGuid>68cf267a-6d40-4404-a430-21a7218d7df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/Housing' and (text() = 'Housing' or . = 'Housing')]</value>
      <webElementGuid>a544bb9f-bb1d-4d51-8b1d-0344adcf291f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
