<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_John Partner_search-choice-close</name>
   <tag></tag>
   <elementGuidId>140d87e3-2202-4b12-9dd7-96871cfb95f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.search-choice-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>114966c4-c9c3-4f7b-93d9-ddd688ba1259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-choice-close</value>
      <webElementGuid>01355522-53d4-416b-887d-a8ae2367159b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>68ce43c2-4249-4c4c-bd82-2e4ef911047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;searchgridsection partselect-action&quot;]/div[@class=&quot;searchbargrid_activeparticipant&quot;]/div[1]/div[@class=&quot;subogrid&quot;]/div[@class=&quot;chosen-container chosen-container-multi chosen-container-active&quot;]/ul[@class=&quot;chosen-choices&quot;]/li[@class=&quot;search-choice&quot;]/a[@class=&quot;search-choice-close&quot;]</value>
      <webElementGuid>a53e57a3-199c-462e-8c72-4ba7871476b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>9dd3c5b9-449f-48de-84dc-e874aafbcf82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
