<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Active</name>
   <tag></tag>
   <elementGuidId>01abe3cc-57e8-43d4-9209-7c843c9e6a7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Review'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.pointer.ng-scope.participant-list-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e31325b6-e4a7-4b4f-9539-7a49be420518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer ng-scope participant-list-active</value>
      <webElementGuid>1e7b8634-802d-4e21-ab02-6014028ffcb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'participant-list-status_active': vmParticipant.IsActiveRecords, 'participant-list-active': !vmParticipant.IsActiveRecords}</value>
      <webElementGuid>95b1a87a-3674-4ef3-bfee-ed4809be02dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmParticipant.getAllParticipant('Active')</value>
      <webElementGuid>2c63ad87-14ac-4912-99a7-fde26eb08f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>isAdmin || isPartner</value>
      <webElementGuid>0641e917-4a12-4f46-aae1-ded39f4cdd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Active 
                                    </value>
      <webElementGuid>bf579603-dd6c-47ee-806a-5c72daaadd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;m-t-20 ng-scope&quot;]/div[@class=&quot;manage_partner ng-scope&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;participant_grid_checklist&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;showingresult-new&quot;]/ul[@class=&quot;participant-list-status&quot;]/li[@class=&quot;pointer ng-scope participant-list-active&quot;]</value>
      <webElementGuid>5156192f-1585-4736-8be9-eb88dbc63546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending Review'])[1]/following::li[1]</value>
      <webElementGuid>864dcbe6-3099-41b6-8297-891771cf8618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Placed'])[1]/preceding::li[1]</value>
      <webElementGuid>f2375a09-b4c6-4850-973e-787bb59c8c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>b9c7eae8-f151-4630-a3f0-e64585aa61c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>ba0de136-c589-412a-9ac0-c20e70b828f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                                        Active 
                                    ' or . = '
                                        Active 
                                    ')]</value>
      <webElementGuid>3c8f4151-6145-4a17-80ed-d1b00b5d4282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
