<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Username_logo</name>
   <tag></tag>
   <elementGuidId>607aed5b-1e04-4330-8209-08a7adb1312b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/div[3]/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ec6d29c5-ab14-4853-8d4d-cef076b17ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dwat.blob.core.windows.net/dwatdevcontainer//UploadedFiles/CompanyLogo//ICES LOGO.png</value>
      <webElementGuid>cd05957a-678b-4b27-8d04-646e5718ef91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>c3444792-ce8e-4d0b-b06b-e1dc7c62a7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>j1ffy logo</value>
      <webElementGuid>b318384d-c66d-4a58-acb3-e8b37df852b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/div[@class=&quot;login_form col-xs-12&quot;]/div[@class=&quot;col-sm-10 col-sm-offset-2 col-xs-12 full_login&quot;]/div[@class=&quot;col-sm-5 col-xs-12&quot;]/div[@class=&quot;login_left&quot;]/div[@class=&quot;logo_inn ng-scope&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>f3b13e44-d53a-4294-9034-eb87efa4b6f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/div[2]/div/div/div/img</value>
      <webElementGuid>57c3823a-9c50-4789-972e-566077509455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='j1ffy logo']</value>
      <webElementGuid>fbf1ac49-2766-4744-8146-adb7ddb8cad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>cfe703b2-fdae-4df9-b848-4a3ce98b6355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dwat.blob.core.windows.net/dwatdevcontainer//UploadedFiles/CompanyLogo//ICES LOGO.png' and @alt = 'j1ffy logo']</value>
      <webElementGuid>d4e9e6c1-ea33-4000-8f02-af7ce5a7a0ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
