<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Go</name>
   <tag></tag>
   <elementGuidId>43ef5262-0a9d-4ad1-9f2a-199e63480c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.custom-create.ctt.m-l-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[3]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b9f7d9e-26f3-4564-98eb-cf6eb74977ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmSlot.getChosenFilters(vmSlot.chosenFiltersForm.$valid)</value>
      <webElementGuid>65fe16e1-edc5-4b47-aa1f-d3abbd102dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-create ctt m-l-10</value>
      <webElementGuid>e4dcda1c-21f0-41e7-9428-cd279e3330c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>38356380-99ef-4405-9a89-e05e2d361858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;btn_action m-0&quot;]/span[1]/a[@class=&quot;custom-create ctt m-l-10&quot;]</value>
      <webElementGuid>5c67da5b-e28b-4e55-b032-d630fbd9f580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[3]/span/a</value>
      <webElementGuid>c3bafaa3-3eb4-436f-8a15-c7315b523132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Go')]</value>
      <webElementGuid>006d5fa5-3341-4f8f-b0ff-5b7398c6f843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::a[1]</value>
      <webElementGuid>7d089b9e-0226-4f67-a02e-da24f961591b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar view'])[1]/preceding::a[1]</value>
      <webElementGuid>cb0c7c5a-cdab-4a6d-8ce1-b00ae446345a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Go']/parent::*</value>
      <webElementGuid>3772f12a-1597-4e9e-ab09-5db7eef58027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>c7d90a54-8431-4383-9ff8-a78660ab0716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Go' or . = 'Go')]</value>
      <webElementGuid>480bb50c-e31f-4e77-ad2b-e769414e1344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
