<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Clear</name>
   <tag></tag>
   <elementGuidId>7c5ada95-d6b7-4d39-b59c-81d6534499b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-align-right.fs-12.pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='vmSlot.chosenFiltersForm']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ee77a07-0088-4c5a-925b-c39c093cba54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmSlot.clearChosenFilters()</value>
      <webElementGuid>626171e8-656b-4443-9edb-26f5eee0ccf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-align-right fs-12 pointer</value>
      <webElementGuid>20cf479c-c7e8-4d83-91bc-f00f1e3c40a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Clear
                                        </value>
      <webElementGuid>2e471ef9-1137-44ec-868e-81e2af4c4e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;text-align-right fs-12 pointer&quot;]</value>
      <webElementGuid>aae6d816-c770-48b4-bed5-7a181307ea07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div[2]</value>
      <webElementGuid>86fa42cf-2d63-41a1-be9e-5eea86a2ed2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::div[1]</value>
      <webElementGuid>0c9c9fec-3167-4382-81b0-cc31e921dc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar view'])[1]/preceding::div[1]</value>
      <webElementGuid>2875c9a1-bd81-46a1-bf79-8397dab2c317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/preceding::div[1]</value>
      <webElementGuid>b3c587b9-1376-43f4-a079-e779b66b057d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear']/parent::*</value>
      <webElementGuid>658ddb3a-9175-4a58-b21b-956b2964c0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]</value>
      <webElementGuid>0cef55e0-e0f4-4e3f-8b88-c5dba14db3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            Clear
                                        ' or . = '
                                            Clear
                                        ')]</value>
      <webElementGuid>b5a6f3a5-fbf4-438d-8dbe-c3641c31475d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
