<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0965e41c-079a-4ef1-9724-099cde2c784a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > p.m-0 > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>475c2ebf-db58-439c-b70d-2e71d4510f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>content/css/img/m-cal-iconnew.png</value>
      <webElementGuid>f3a795b1-b161-4acf-8a48-b03b23c86271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;manage_partner&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-md-12 col-sm-12 dashboard cal_view p-b-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-12&quot;]/div[@class=&quot;customm-r&quot;]/ul[@class=&quot;filter-choose flexinline&quot;]/li[2]/p[@class=&quot;m-0&quot;]/a[1]/img[1]</value>
      <webElementGuid>97e48357-ac81-4aff-8e38-c3c45ca65bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/p/a/img</value>
      <webElementGuid>668c77b8-b3f5-4b5d-bd0e-74e16735bbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'content/css/img/m-cal-iconnew.png']</value>
      <webElementGuid>2e127190-b525-482c-8aaf-7643a378abbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
