<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>d84851ec-7e62-4102-832d-43c40d05d5b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.m-0 > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>205d14f6-f82b-445b-bbd6-011f4862d570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>content/css/img/da-cal-iconnew.png</value>
      <webElementGuid>47abb5ab-206f-44f4-b090-c6fdf723c1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[1]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;content-body&quot;]/div[@class=&quot;margin-top-value margin ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/div[@class=&quot;manage_partner&quot;]/div[@class=&quot;container-fluid full_bg nopadding&quot;]/div[@class=&quot;col-md-12 col-sm-12 dashboard cal_view p-b-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-3 col-md-3 col-sm-12&quot;]/div[@class=&quot;customm-r&quot;]/ul[@class=&quot;filter-choose flexinline&quot;]/li[1]/p[@class=&quot;m-0&quot;]/a[1]/img[1]</value>
      <webElementGuid>eef5656d-37da-499d-acbf-21dcdc796a91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>a7275bb1-15b5-44fe-9b10-04805e11464a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'content/css/img/da-cal-iconnew.png']</value>
      <webElementGuid>7d1d7267-acc7-4cab-934d-4849687d8c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
