<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month                               _d53c4c</name>
   <tag></tag>
   <elementGuidId>7301f540-47bf-4ae1-bd68-42f627ebc8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d9d5b39-91c1-4757-acfc-c38bd7246fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control m-r-5 ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>d67b8495-d192-4085-a080-043392d9f91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>16d89e7d-01a5-40f8-9221-947dca8a3460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Browse by Month</value>
      <webElementGuid>16356428-cc3b-4138-9b15-44cc2d26d0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmSlot.ChoosefilterData.Month</value>
      <webElementGuid>a6bc2d05-b200-43c7-a753-d7aa578be14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                </value>
      <webElementGuid>ba5b8583-e0f7-4cf1-94dc-752e70da2790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;browse position-relative&quot;]/select[@class=&quot;minimal form-control m-r-5 ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>dc3c90a2-1861-4e8c-bfe6-6dd5fad71ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Month']</value>
      <webElementGuid>f5b8a5de-01df-4168-acb2-410c9c035643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div/select</value>
      <webElementGuid>b2bd6aff-6707-431c-adcd-4eaa03d3a13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::select[1]</value>
      <webElementGuid>4652ad71-574e-4603-bd90-e0c2e3889ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[2]</value>
      <webElementGuid>18496f81-da70-4cdb-abda-95c5e728f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9dd5d8e6-29c4-447b-9034-4ce44e4bde13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Month' and @placeholder = 'Browse by Month' and (text() = '
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                ' or . = '
                                                    Month
                                                    JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember
                                                ')]</value>
      <webElementGuid>4fba28b0-998f-4d99-876b-4b12d9a2c13e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
