<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year                                _78bea1</name>
   <tag></tag>
   <elementGuidId>e964060f-9bd8-4b12-8038-6a41225a362f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;Year&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='Year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e01214fa-e442-4269-98fe-599adc097fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>9f3971d1-5a1f-4d77-b5b4-91a8694cfe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Year</value>
      <webElementGuid>b795cfc6-9e85-433d-b3d1-76f756d56263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmSlot.ChoosefilterData.Year</value>
      <webElementGuid>645594a0-e91f-458d-8e10-8fff567f8834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                </value>
      <webElementGuid>6ce367ee-fe8a-466a-835e-a709addd600e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vmSlot.chosenFiltersForm&quot;)/div[@class=&quot;m-t-20&quot;]/div[@class=&quot;d-flex fl_bw&quot;]/div[@class=&quot;browse position-relative&quot;]/select[@class=&quot;minimal form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>f987407b-0cbe-479b-8458-c9263c1b11aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='Year']</value>
      <webElementGuid>e0a3ee20-aa54-48c4-b680-eb96ecfa057a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vmSlot.chosenFiltersForm']/div/div/div[2]/select</value>
      <webElementGuid>e5895871-1fe7-408f-8d9f-c2a4f6c67f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Settings'])[1]/following::select[2]</value>
      <webElementGuid>0eda81ac-3120-4243-a6d9-6c6e862a8daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>c426ec9a-921c-49ed-9603-efa6a0630cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>822bfd0b-c1a3-4366-8f98-bd6f4cbab3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Year' and (text() = '
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                ' or . = '
                                                    Year
                                                    2023
                                                    2024
                                                    2025
                                                    2026
                                                ')]</value>
      <webElementGuid>3ebff048-0ae4-40ae-8525-191a0afedf7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
